### ISSUE TITLE
Missing DOIs in JOSS paper

### ISSUE THREAD

**Issue by nhejazi** [oneilsh/tidytensor#4]
Please update `paper.bib` for the JOSS paper to include DOIs for the two manuscripts cited, Baydin et al. (2018) in JMLR and Hoyer & Hamman (2017) in JOSS. This is an easily resolved blocker for the "Software Paper" component of the ongoing review in https://github.com/openjournals/joss-reviews/issues/3543.

**Comment by oneilsh** [comment]
Hi @nhejazi, thanks for the comment, using DOIs is a good practice I agree, especially in our link-all-the-data world :) Two questions though: I think that the Hoyer et al. paper has a DOI, though perhaps it showed up in my updated .bib addressing the other reviewer, link to that updated compiled PDF is here: https://github.com/oneilsh/tidytensor/suites/3607702673/artifacts/87088522

For Bayden et al., I'm having trouble locating a proper DOI. I did find this one: https://dl.acm.org/doi/10.5555/3122009.3242010 but that doesn't look like a proper DOI as it doesn't resolve at https://doi.org. Perhaps I should add the https://dl.acm.org/doi/10.5555/3122009.3242010 link as a URL rather than DOI entry?

Thanks!
~Shawn

**Comment by nhejazi** [comment]
Thanks for pointing out the updated paper draft @oneilsh, I'd missed that in my initial review. The reference to the Hoyer et al. paper LGTM. For the Bayden et al. paper, I'm similarly unable to track down a URL but I think it probably will do to just use the JMLR URL (https://jmlr.org/papers/v18/17-468.html) or the URL referenced in the bibTeX entry on the website.

**Comment by oneilsh** [comment]
Ok, added the URL, preview build here: https://github.com/oneilsh/tidytensor/suites/3678404962/artifacts/89563033

Thanks again!
